# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681a7b17fc423fedf31cef6b4fdd63908d9586e012d896c98088671864403e62ce870615b4d0d9b584a85d43b709f3c42ec5ceed47cd320623f7ef11fb14e480

test:
  secret_key_base: 6b62917aadcf747389be89e1a89c990fbdaf00beb2517954ad9d94b1bc21d94cd3b7993c8445914e886f1c6d44753b93526a35bd79506a5d22cb44f1c7fc4009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
